
DROP TABLE menschen CASCADE CONSTRAINT;
DROP TABLE training CASCADE CONSTRAINT;
DROP TABLE gericht CASCADE CONSTRAINT;
DROP TABLE mitglied CASCADE CONSTRAINT;
DROP TABLE mitarbeiter CASCADE CONSTRAINT;
DROP TABLE produkt CASCADE CONSTRAINT;
DROP TABLE isst CASCADE CONSTRAINT; 
DROP TABLE verkauft CASCADE CONSTRAINT;
DROP SEQUENCE sequenz_id; 
DROP VIEW view_name;
DROP VIEW view_join;
DROP VIEW view_member_node;
DROP VIEW view_employe_node;